

## Demo 3: File Handling In NumPy

In this demo, you will be shown how to handle files in numpy.

### Loading and Saving Data in Binary file

In [1]:
#Import the library
import numpy as np

In [2]:
#Creating the array using zeros() and ones()
a = np.zeros((3,3))
b = np.ones((3,3))
print('a=',a)
print('b=',b)

a= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
b= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
#SavE arrays to binary file
np.save('file1.npy',(a,b))

In [4]:
#Load data from binary file
c=np.load('file1.npy')
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### Loading and Saving data in text and csv file

In [5]:
#Import the library
import numpy as np

In [6]:
#Create an array
a = np.arange(0,10,1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
#Save array to text file and reading the file
b = np.savetxt('file2.txt', a, delimiter =', ')    
c = open("file2.txt", 'r')# open file in read mode 
  
print("the file contains:") 
print(c.read()) 

the file contains:
0.000000000000000000e+00
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00
7.000000000000000000e+00
8.000000000000000000e+00
9.000000000000000000e+00



In [8]:
#Recover data from text file
d=np.genfromtxt('file2.txt')
print(d)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [9]:
#Load a marks.csv file 
data = np.loadtxt('marks.csv',delimiter=',',usecols=(5),skiprows=1)
data

array([420., 280., 350., 269., 317., 470., 333., 365., 305., 350., 460.,
       474., 409., 377., 415., 382., 298., 462., 370., 313., 464., 302.,
       252., 259., 308., 392., 424., 403., 370., 328., 398., 434., 291.,
       472., 263., 439., 464., 449., 401., 364., 296., 292., 438., 357.,
       331., 317., 429., 407., 321., 274., 447., 274., 437., 411., 257.,
       310., 396., 270., 311., 459., 378., 316., 283., 266., 381., 409.,
       313., 306., 448., 348., 292., 400., 352., 441., 428., 309., 441.,
       439., 264., 281., 302., 432., 423., 336., 383., 321., 469., 270.,
       341., 281., 403., 333., 323., 348., 345., 397., 449., 261., 456.,
       370., 322., 379., 446., 404., 301., 254., 351., 444., 264., 286.,
       463., 273., 316., 324., 465., 398., 324., 340., 414., 346., 408.,
       332., 394., 474., 398., 262., 410., 391., 444., 461.])

#### Conclusion: This code demonstrates how to perform file handling in numpy