# NumPy: Numerical Python
    - Multidimensional array objects and methods associated
    - Random number generation and operation
    - Linear Algebra Functions

In [1]:
import numpy as np

In [4]:
# Arrays: 
#sales of 20 stores for a month
#list: dictionary: 20 keys


In [5]:
sales = [[1, 1, 3, 2, 4], [2, 1, 4, 3,  1], [3,2,  1, 4,5 ], [6, 2, 3, 5, 1], [1, 4, 3,4, 2]]
#sales for each store:


In [6]:
for i in sales:
    print(sum(i))

11
11
15
17
14


In [144]:
#creating an array

In [145]:
sales_arr = np.array([1000, 2000, 870, 780, 1500, 1450, 1700])

In [146]:
print('Array Data :\n', sales_arr)
print('Array dimensions: \t:{}'.format(sales_arr.ndim)) #How many elements in each dimension
print('Array Shape \t:{}'.format(sales_arr.shape))
print('Array Size \t:{}'.format(sales_arr.size))
print('Array Data Type \t:{}'.format(sales_arr.dtype))
print('Array Item Size \t:{}'.format(sales_arr.itemsize)) #Size in bytes

Array Data :
 [1000 2000  870  780 1500 1450 1700]
Array dimensions: 	:1
Array Shape 	:(7,)
Array Size 	:7
Array Data Type 	:int64
Array Item Size 	:8


In [147]:
store1 = [1000, 1200, 870, 780, 1500, 1450, 1700]
store2 = [780, 75, 1145, 1345, 1400, 670, 2000]
store3 = [1167, 1560, 1899, 1900, 1654, 1000, 1900]
store4 = [1145, 1180, 1800, 2100, 1245, 1900, 2125]
store5 = [1160, 1780, 2100, 810, 1090, 1100, 1560]

sales_list = [store1, store2, store3, store4, store5]
sales_list


[[1000, 1200, 870, 780, 1500, 1450, 1700],
 [780, 75, 1145, 1345, 1400, 670, 2000],
 [1167, 1560, 1899, 1900, 1654, 1000, 1900],
 [1145, 1180, 1800, 2100, 1245, 1900, 2125],
 [1160, 1780, 2100, 810, 1090, 1100, 1560]]

In [148]:
sales_arr = np.array(sales_list)
print('Array Data :\n', sales_arr)
print('Array dimensions: \t:{}'.format(sales_arr.ndim)) #How many elements in each dimension
print('Array Shape \t:{}'.format(sales_arr.shape))
print('Array Size \t:{}'.format(sales_arr.size))
print('Array Data Type \t:{}'.format(sales_arr.dtype))
print('Array Item Size \t:{}'.format(sales_arr.itemsize)) #Size in bytes

Array Data :
 [[1000 1200  870  780 1500 1450 1700]
 [ 780   75 1145 1345 1400  670 2000]
 [1167 1560 1899 1900 1654 1000 1900]
 [1145 1180 1800 2100 1245 1900 2125]
 [1160 1780 2100  810 1090 1100 1560]]
Array dimensions: 	:2
Array Shape 	:(5, 7)
Array Size 	:35
Array Data Type 	:int64
Array Item Size 	:8


In [149]:
np.array([1234, 23.44, 34])

array([1234.  ,   23.44,   34.  ])

In [150]:
np.array([1234, 23.45, True, '34'], dtype = int)

array([1234,   23,    1,   34])

In [151]:
#Hierarchy String > float > int

In [152]:
#Arrays filed with zeros with numpy:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [153]:
np.zeros((5, 4), dtype = str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [154]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [155]:
np.zeros_like(sales_arr)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [156]:
np.random.randint(2, 100, (5, 4)) #Array filled with random numbers between 2 and 100 of shape 5x4 

array([[21, 84, 28, 63],
       [15, 72, 46, 31],
       [25, 56, 55, 99],
       [36, 91, 30, 33],
       [ 5, 87, 59, 65]])

In [157]:
np.linspace(1, 100, 10, retstep = True) #Array with equally steppd numbers inclusive of 1 and 100 with 10 numbers

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [158]:
np.arange(1, 100, 10) #start, stop, and step value stop is excluded

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [159]:
sales_stores_arr = np.array([1000, 2000, 870, 780, 1500, 1450, 1700])

In [160]:
sales_stores_arr

array([1000, 2000,  870,  780, 1500, 1450, 1700])

In [161]:
sum(sales_stores_arr)

9300

In [162]:
per_arr = sales_stores_arr / sum(sales_stores_arr) * 100 #sales as percentage

In [163]:
per_arr

array([10.75268817, 21.50537634,  9.35483871,  8.38709677, 16.12903226,
       15.59139785, 18.27956989])

In [164]:
per_arr.round(2)

array([10.75, 21.51,  9.35,  8.39, 16.13, 15.59, 18.28])

In [165]:
print('Sum\t:', sales_stores_arr.sum())

Sum	: 9300


In [166]:
print('Sum\t:', sales_stores_arr.cumsum()) #Cumulative sum

Sum	: [1000 3000 3870 4650 6150 7600 9300]


In [167]:
print('Max Value\t:', sales_stores_arr.max()) #<Max value

Max Value	: 2000


In [168]:
print('Min Value\t:', sales_stores_arr.min()) #<Max value

Min Value	: 780


In [169]:
print('Mean Value\t:', sales_stores_arr.mean(), 2) #<Max value

Mean Value	: 1328.5714285714287 2


In [170]:
print('Var Value\t:', sales_stores_arr.var(), 2) #<Max value

Var Value	: 178869.38775510204 2


## 2 Dimensional Array

In [171]:
sales_arr

array([[1000, 1200,  870,  780, 1500, 1450, 1700],
       [ 780,   75, 1145, 1345, 1400,  670, 2000],
       [1167, 1560, 1899, 1900, 1654, 1000, 1900],
       [1145, 1180, 1800, 2100, 1245, 1900, 2125],
       [1160, 1780, 2100,  810, 1090, 1100, 1560]])

In [172]:
print('Sum\t:', sales_arr.sum())
print('Sum\t:', sales_arr.cumsum()) #Cumulative sum
print('Max Value\t:', sales_arr.max()) #<Max value
print('Min Value\t:', sales_arr.min()) #<Max value
print('Mean Value\t:', sales_arr.mean(), 2) #<Max value
print('Var Value\t:', sales_arr.var(), 2) #<Max valu

Sum	: 48090
Sum	: [ 1000  2200  3070  3850  5350  6800  8500  9280  9355 10500 11845 13245
 13915 15915 17082 18642 20541 22441 24095 25095 26995 28140 29320 31120
 33220 34465 36365 38490 39650 41430 43530 44340 45430 46530 48090]
Max Value	: 2125
Min Value	: 75
Mean Value	: 1374.0 2
Var Value	: 226097.0285714286 2


## Along an Axis:

In [173]:
#For a 2d array 
#Axis = 0 Column Wise Operation
#Axis = 1 Row-wise operation

print('for each store IE Row-wize operation'.upper())
print('Sum\t:', sales_arr.sum(axis=1))
print('Cumulative Sum\t:', sales_arr.cumsum(axis=1)) #Cumulative sum
print('Max Value\t:', sales_arr.max(axis=1)) #<Max value
print('Min Value\t:', sales_arr.min(axis=1)) #<Max value
print('Mean Value\t:', sales_arr.mean(axis=1), 2) #<Max value
print('Var Value\t:', sales_arr.var(axis=1), 2) #<Max valu

FOR EACH STORE IE ROW-WIZE OPERATION
Sum	: [ 8500  7415 11080 11495  9600]
Cumulative Sum	: [[ 1000  2200  3070  3850  5350  6800  8500]
 [  780   855  2000  3345  4745  5415  7415]
 [ 1167  2727  4626  6526  8180  9180 11080]
 [ 1145  2325  4125  6225  7470  9370 11495]
 [ 1160  2940  5040  5850  6940  8040  9600]]
Max Value	: [1700 2000 1900 2125 2100]
Min Value	: [ 780   75 1000 1145  810]
Mean Value	: [1214.28571429 1059.28571429 1582.85714286 1642.14285714 1371.42857143] 2
Var Value	: [103767.34693878 326910.20408163 117049.83673469 164663.26530612
 178012.24489796] 2


In [174]:
#For a 2d array 
#Axis = 0 Column Wise Operation
#Axis = 1 Row-wise operation

print('for each store IE Column-wize operation'.upper())
print('Sum\t:', sales_arr.sum(axis=1))
print('Cumulative Sum\t:', sales_arr.cumsum(axis=0)) #Cumulative sum
print('Max Value\t:', sales_arr.max(axis=0)) #<Max value
print('Min Value\t:', sales_arr.min(axis=0)) #<Max value
print('Mean Value\t:', sales_arr.mean(axis=0), 2) #Mean value
print('Var Value\t:', sales_arr.var(axis=0), 2) #Var value

FOR EACH STORE IE COLUMN-WIZE OPERATION
Sum	: [ 8500  7415 11080 11495  9600]
Cumulative Sum	: [[1000 1200  870  780 1500 1450 1700]
 [1780 1275 2015 2125 2900 2120 3700]
 [2947 2835 3914 4025 4554 3120 5600]
 [4092 4015 5714 6125 5799 5020 7725]
 [5252 5795 7814 6935 6889 6120 9285]]
Max Value	: [1167 1780 2100 2100 1654 1900 2125]
Min Value	: [ 780   75  870  780 1090  670 1560]
Mean Value	: [1050.4 1159.  1562.8 1387.  1377.8 1224.  1857. ] 2
Var Value	: [ 22042.64 344724.   222481.36 294936.    38435.36 176104.    41396.  ] 2


In [175]:
np.sqrt
np.sin
np.log
np.greater

<ufunc 'greater'>

In [176]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [177]:
x1 = np.array([2, 4, 1, 5, 6])
x2 = np.array([3, 5, 1, 3, 6])

In [178]:
np.logical_and(x1 < 2.5, x2 < 2.5)


array([False, False,  True, False, False])

In [179]:
np.logical_or(x1 < 2.5, x2 < 2.5)

array([ True, False,  True, False, False])

In [180]:
np.logical_not(x1 < 2.5)

array([False,  True, False,  True,  True])

In [181]:
np.logical_xor(x1 < 2.5, x2 < 2.5)

array([ True, False, False, False, False])

In [182]:
ratings = np.array([00, 1, 3, 4, 2, 3, 3, 3, 4, 5, 2, 10, 3, 3]* 100)
ratings.shape

(1400,)

In [183]:
np.any(ratings > 5) #Used to check if a single value in the array is true

True

In [184]:
np.all(ratings <= 5) #used to check if all values evalue to true

False

In [185]:
ht = np.array([1.77, 1.67, 1.56, 1.76, 1.70])
wt = np.array([80, 91, 87, 76, 90])

In [186]:
bmi = wt/(ht**2)

In [187]:
bmi


array([25.53544639, 32.62935207, 35.7495069 , 24.53512397, 31.14186851])

## Matrix Product: No Elementize Computation

In [188]:
a1 = np.random.randint(1, 10, (2, 4))
a2 = np.random.randint(1, 10, (4, 5))

In [189]:
a1

array([[5, 4, 7, 8],
       [9, 5, 5, 4]])

In [190]:
a2

array([[9, 5, 1, 8, 3],
       [3, 3, 6, 2, 8],
       [2, 8, 6, 9, 4],
       [4, 7, 3, 9, 8]])

### Indexing An Array

In [191]:
lis = ['A', 1, 'B', 2, 'C', 3, 'D', 4, 'E', 5]
lis[0]

'A'

In [192]:
sales_arr

array([[1000, 1200,  870,  780, 1500, 1450, 1700],
       [ 780,   75, 1145, 1345, 1400,  670, 2000],
       [1167, 1560, 1899, 1900, 1654, 1000, 1900],
       [1145, 1180, 1800, 2100, 1245, 1900, 2125],
       [1160, 1780, 2100,  810, 1090, 1100, 1560]])

In [193]:
sales_stores_arr

array([1000, 2000,  870,  780, 1500, 1450, 1700])

In [194]:
sales_stores_arr[0]

1000

### Slicing In Arrays

In [195]:
sales_stores_arr[1:10:2]

array([2000,  780, 1450])

In [196]:
rand_arr_id = np.random.randint(1, 10, 20)

In [197]:
rand_arr_id

array([4, 7, 8, 5, 2, 4, 8, 8, 9, 8, 8, 2, 4, 2, 8, 8, 4, 9, 8, 4])

In [198]:
rand_arr_id[1:10:2]

array([7, 5, 4, 8, 8])

In [199]:
#For two dimensional arrays: arr_2d[row, column]
rand_arr_2d = np.random.randint(1, 10, (5, 4))

In [200]:
rand_arr_2d

array([[1, 8, 4, 6],
       [4, 9, 9, 5],
       [6, 7, 4, 4],
       [5, 4, 3, 4],
       [5, 7, 3, 2]])

In [201]:
rand_arr_2d[2]

array([6, 7, 4, 4])

In [202]:
#A complete column:
rand_arr_2d[:, 3]

array([6, 5, 4, 4, 2])

In [203]:
#To extract as 2d need to correlate in form of a list:
rand_arr_2d[[2]]

array([[6, 7, 4, 4]])

In [204]:
rand_arr_2d[:, [3]]

array([[6],
       [5],
       [4],
       [4],
       [2]])

In [205]:
rand_arr_2d[4, 3]

2

### Array Manipulations

In [206]:
sales_arr

array([[1000, 1200,  870,  780, 1500, 1450, 1700],
       [ 780,   75, 1145, 1345, 1400,  670, 2000],
       [1167, 1560, 1899, 1900, 1654, 1000, 1900],
       [1145, 1180, 1800, 2100, 1245, 1900, 2125],
       [1160, 1780, 2100,  810, 1090, 1100, 1560]])

In [207]:
#Correct 75 in array
sales_arr[1, 1] = 750 #Assigning to 750

In [208]:
sales_arr

array([[1000, 1200,  870,  780, 1500, 1450, 1700],
       [ 780,  750, 1145, 1345, 1400,  670, 2000],
       [1167, 1560, 1899, 1900, 1654, 1000, 1900],
       [1145, 1180, 1800, 2100, 1245, 1900, 2125],
       [1160, 1780, 2100,  810, 1090, 1100, 1560]])

### Changing Array Shapes

In [209]:
rand_arr_2d

array([[1, 8, 4, 6],
       [4, 9, 9, 5],
       [6, 7, 4, 4],
       [5, 4, 3, 4],
       [5, 7, 3, 2]])

### To Convert to a 1D Array

In [210]:
rand_arr_2d.ravel(order='C') #In 'C' order:

array([1, 8, 4, 6, 4, 9, 9, 5, 6, 7, 4, 4, 5, 4, 3, 4, 5, 7, 3, 2])

In [211]:
rand_arr_2d.flatten(order='F') #Flatten Array

array([1, 4, 6, 5, 5, 8, 9, 7, 4, 7, 4, 9, 4, 3, 3, 6, 5, 4, 4, 2])

In [212]:
#For reshaping the size remains the same


### Transpose Function

In [213]:
sales_arr.T

array([[1000,  780, 1167, 1145, 1160],
       [1200,  750, 1560, 1180, 1780],
       [ 870, 1145, 1899, 1800, 2100],
       [ 780, 1345, 1900, 2100,  810],
       [1500, 1400, 1654, 1245, 1090],
       [1450,  670, 1000, 1900, 1100],
       [1700, 2000, 1900, 2125, 1560]])

### Concatenate - To Join Arrays

In [214]:
x1 = np.array([[10, 20, 30], [20, 40, 60]])
x2 = np.array([[100, 200, 300]])

In [215]:
np.concatenate([x1, x2], axis=None)

array([ 10,  20,  30,  20,  40,  60, 100, 200, 300])

In [233]:
np.concatenate([x1, x2], axis=0) #Column-wise operation

array([1, 2, 3, 4, 5, 6])

In [234]:
x3 = np.array([[100, 200], [300, 400]])
x3.shape

(2, 2)

### Stack Functions - Stack, HStack, VStack

In [225]:
#Stack
#hstack
#vstack

x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])
np.stack((x1, x2))



array([[1, 2, 3],
       [4, 5, 6]])

In [226]:
np.hstack((x1, x2))

array([1, 2, 3, 4, 5, 6])

In [227]:
np.vstack((x1, x2))

array([[1, 2, 3],
       [4, 5, 6]])

### Split Functions - HSplit, VSplit

In [228]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [229]:
np.split(x, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [230]:
x = np.arange(16).reshape((4, 4))

In [231]:
np.hsplit(x, 2) #Split at column 2

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [232]:
np.vsplit(x, 2) #Split at row 2

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]